// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistance;

namespace Persistance.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Domain.Milestone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentMilestoneId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParentProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(2);

                    b.HasKey("Id");

                    b.HasIndex("ParentMilestoneId");

                    b.HasIndex("ParentProjectId")
                        .IsUnique();

                    b.ToTable("Milestones");
                });

            modelBuilder.Entity("Domain.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Domain.Milestone", b =>
                {
                    b.HasOne("Domain.Milestone", "ParentMilestone")
                        .WithMany("SubMilestones")
                        .HasForeignKey("ParentMilestoneId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Project", "ParentProject")
                        .WithOne("RootMilestone")
                        .HasForeignKey("Domain.Milestone", "ParentProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentMilestone");

                    b.Navigation("ParentProject");
                });

            modelBuilder.Entity("Domain.Milestone", b =>
                {
                    b.Navigation("SubMilestones");
                });

            modelBuilder.Entity("Domain.Project", b =>
                {
                    b.Navigation("RootMilestone");
                });
#pragma warning restore 612, 618
        }
    }
}
