name: Build and test NodeJS app

on:
  push:
    branches-ignore:
      - 'master'
    paths-ignore:
      - '.github/**'

jobs:
  build-and-test-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web

    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
