# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Build and deploy NodeJS app to Azure

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - 'api/**'
      - '.github/**'

jobs:
  build-test-and-deploy-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Run Azure webapp deploy action using publish profile credentials
        uses: azure/webapps-deploy@v2
        with:
          app-name: roadmap-web-dev
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_90A50E30E21F42239AE0C20652A8B4CE }}
          package: /home/runner/work/InteractiveProjectRoadmap/InteractiveProjectRoadmap/web/build
